const tableData4 = {
    columnName: ["ELECTRICAL", "INSTRUMENTATION", "CIVIL / STRUCTURAL / ARCHITECTURAL"],
    tableDataCol1: ["Electrical Design Basis Memorandum", "Single Line Diagram", "Cable Schedule",
        "Electrical Equipment, Cables Sizing Calculations", "Change Over Procedure",
        "Data Sheets", "Demolition Drawings", "Earthing & Cable Routing Layouts",
        "Electrical Design Philosophy", "Lighting Layout", "Load Schedule",
        "Electrical Equipment Layout", "Electrical Equipment Schedule", "Electrical Tie-In Schedule",
        "Installation Drawings", "Materials Requisitions & Subcontracts",
        "Materials Take Offs / Bill Of Quantities", "Electrical Specifications",
        "Technical Bids Evaluation"],
    tableDataCol2: ["Instrumentation Design Basis Memorandum", "Alarm & Trip Index",
        "Cable Routing Location Drawings", "Control System Block Diagram",
        "Data Sheets", "I/O List", "Instrument Index", "Junction Box Schedule",
        "Materials Requisitions & Subcontracts", "Materials Take Offs / Bill Of Quantities",
        "RTU/SCADA/IPS", "Technical Specification", "Wiring Interconnection Diagrams"],
    tableDataCol3: ["CSA Design Basis Memorandum", "Building GA and Details", "Civil Layout Plan",
        "Design Calculations", "Equipment Foundation Layout and Details",
        "Pipe racks structural and foundations drawings", "Materials Requisitions & Subcontracts",
        "Materials Take Offs / Bill Of Quantities", "Site Grading Plan",
        "Drainage and Sewerage Design", "Civil, Structural and Architectural Specifications",
        "Specifications for Topographic Survey", "Specifications for Geotechnical Investigation",
        "Technical Bids Evaluation", "Civil, Structural, Steel and Rebar Detailing"],
};

export default tableData4;
