const tableData2 = {
    columnName: ["Process",
        "Process Safety",
        "Piping",
        "Pipeline",
        "Mechanical",
        "Electrical",
        "Instrumentation & Controls",
        "Civil / Structural / Architectural"],
    tableDataCol1: ["Process Design Memorandum",
        "Process Simulations",
        "Hydraulics & Sizing",
        "Hydraulic Calculation",
        "P&ID & Mass Balance",
        "Heat & Mass Balance",
        "Process Instrumentation Diagrams",
        "Process Flow Diagrams",
        "Utility Flow Diagrams",
        "Process Description",
        "Change Over Procedure",
        "Data Sheets",
        "Equipment List",
        "HAZID / HAZOP Report",
        "Line List",
        "Material Selection Diagram",
        "Materials & Requisitions",
        "Subcontracting & Operations Control",
        "Philosophy"],
    tableDataCol2: ["Process Safety Management Plan (PSM)",
        "Risk Management Plan (RMP)",
        "IEC 61511 Gap Assessment",
        "Independent Protection Layer (IPL)",
        "Safety Integrity Layer (SIL)",
        "Process Hazard Analysis (PHA)",
        "Layers of Protection Analysis (LOPA)",
        "Facility Siting Analysis"],
    tableDataCol3: ["Piping Design Basis Memorandum",
        "Plot Plan",
        "3D Modeling",
        "General Arrangement Drawing",
        "Tie-in Schedule",
        "Valve Data Sheets",
        "Materials & Subcontracts",
        "Bill of Quantities",
        "Pipe Support Details",
        "Calculations",
        "Piping General Arrangement Drawings",
        "Piping Demolition Drawings",
        "Analysis",
        "Piping Specifications",
        "Technical Bids Evaluation"],
    tableDataCol4: ["Pipeline Design Basis Memorandum",
        "Alignment Sheets",
        "Bill of Materials",
        "Construction Planning",
        "Crossing Sheets",
        "Data Sheets",
        "Field Area Arrangement",
        "General Line Drawing",
        "Line Routing Maps",
        "Materials & Subcontracts",
        "Plot Plan",
        "Reports",
        "Route Maps & Town Planning",
        "Specifications",
        "Drawing Approach",
        "Technical Bids Evaluation",
        "Topographic Works",
        "Typical Drawings"],
    tableDataCol5: ["Mechanical Design Basis Memorandum",
        "Material Selection & Corrosion",
        "Equipment Sizing",
        "Equipment Data Sheets",
        "Piping Specialty List",
        "Heating Ventilation & Air Conditioning (HVAC)",
        "Materials",
        "Mechanical Subcontracts",
        "Equipment Specification",
        "Technical Bids Evaluation"],
    tableDataCol6: ["Electrical Design Basis Memorandum",
        "Single Line Diagram",
        "Cable Schedule",
        "Equipment, Cables Sizing Calculations",
        "Change Over Procedure",
        "Data Sheets",
        "Protection",
        "Drawings",
        "Routing Layouts",
        "Electrical Design Philosophy",
        "Lighting Layout",
        "Load Schedule",
        "Equipment Layout",
        "Equipment Schedule",
        "Installation Schedule",
        "Drawings",
        "Materials",
        "Subcontracts",
        "Materials Take Offs",
        "Bill of Quantities"],
    tableDataCol7: ["Design Basis Memorandum",
        "Alarm & Trip Index",
        "Cable Routing & Instrument Block Diagram",
        "Cable Schedule",
        "Instrument Block Diagram",
        "Data Sheets",
        "I/O List",
        "Instrument Hook-up Details",
        "Instrument Index",
        "Junction Box Schedule",
        "Materials & Subcontracts",
        "Materials Take Offs",
        "Bill of Quantities",
        "RSV/DCS/DCS/IPS",
        "Instrumentation Specifications",
        "Technical Bids Evaluation",
        "Wiring Interconnection Diagrams"],
    tableDataCol8: ["CSA Design Basis Memorandum",
        "Building GA and Detail Layout",
        "Civil Layout Plan Designs",
        "Foundation Calculations and Details",
        "Design Layout",
        "Materials & Subcontracts",
        "Bill of Quantities",
        "Site Grading Plan",
        "Drainage and Sewerage Design",
        "Civil, Structural and Architectural Specifications",
        "Topography for Specifications",
        "Geotechnical Specifications",
        "Technical Bids Evaluation",
        "Civil, Structural, Steel and Rebar Detailing"],
};

export default tableData2;
