const tableData7 = {
    columnName: ["Project Management Software"],
    tableDataCol1: ["Integrated Project Management System", "Scheduling", "Cost Estimation", "Office", "Process Simulation",
        "Corrosion Evaluation",
        "RAM Study",
        "CAD",
        "HVAC - Thermal Design",
        "Pressure Vessel Design",
        "Piping Stress Analysis",
        "Electrical Design",
        "Lighting Calculations",
        "Instrumentation Design",
        "Civil Structural Design"],
    tableDataCol2: ["Wrench SmartProject", "MS Project Primavera", "ASPEN In-Plant, Excel", "MicroSoft Office", "Aspen, HYSYS, Unisim",
        "Intercorr",
        "Maros",
        "AutoCAD 2D & 3D, SP3, PDS",
        "Career",
        "PV Elite",
        "Ceasar II",
        "ETAP",
        "Dialux",
        "Intools",
        "SACS, STAAD Pro, Tekla"],
};

export default tableData7;
