const tableData = {
    columnName: ["Process Studies", "Engineering & Procurement", "Project Management"],
    tableDataCol1: ["Concept Development",
        "Facilities Design",
        "Process Engineering",
        "Facilities Evaluation",
        "Revamps and Upgrades",
        "Debottlenecking",
        "Optimization"],
    tableDataCol2: ["Feasibility studies",
        "Scoping (FEL I)",
        "Pre-FEED (FEL II)",
        "FEED (FEL III)",
        "Detailed engineering",
        "Procurement Services",
        "Fabrication Design and Management"],
    tableDataCol3: ["Owner’s Engineering",
        "Project Management Consultant",
        "Project Controls",
        "Construction Management",
        "Quality Assurance and Control",
        "Safety and Reliability",
        "Commissioning and Start-up"],
};

export default tableData;
