name:  CI/CD

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - 'main'
  

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Checkout code
      - name: Checkout client
        uses: actions/checkout@v4

      # Use Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Setup and start Node.js backend
      - name: Install backend dependencies
        working-directory: backendnew
        run: npm install

      - name: Start backend with PM2
        working-directory: backendnew
        run: pm2 restart backend

      # Setup and build Tube1 (landing page)
      - name: Install Tube1 dependencies
        working-directory: tube1
        run: npm install

      - name: Build Tube1 (landing page)
        working-directory: tube1
        run: npm run build

      - name: Restart Tube1 with PM2
        working-directory: tube1
        run: pm2 restart landingpage

      # Setup and build Tube2 (admin panel)
      - name: Install Tube2 dependencies
        working-directory: tube2
        run: npm install

      - name: Build Tube2 (admin panel)
        working-directory: tube2
        run: npm run build

      - name: Restart Tube2 with PM2
        working-directory: tube2
        run: pm2 restart adminpanel
